import type { ProduceCategory, Unit } from '@farmgo/db';

/** Starter produce catalog with Kiswahili names, typical for hotel and restaurant kitchens. */
export const PRODUCE: {
  slug: string;
  name: string;
  nameSw: string;
  category: ProduceCategory;
  unit: Unit;
  shelfLifeDays: number;
}[] = [
  {
    slug: 'tomatoes',
    name: 'Tomatoes',
    nameSw: 'Nyanya',
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 7,
  },
  {
    slug: 'onions-red',
    name: 'Red onions',
    nameSw: 'Vitunguu vyekundu',
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 30,
  },
  {
    slug: 'kale',
    name: 'Kale (sukuma wiki)',
    nameSw: 'Sukuma wiki',
    category: 'VEGETABLE',
    unit: 'BUNCH',
    shelfLifeDays: 3,
  },
  {
    slug: 'spinach',
    name: 'Spinach',
    nameSw: 'Spinachi',
    category: 'VEGETABLE',
    unit: 'BUNCH',
    shelfLifeDays: 3,
  },
  {
    slug: 'cabbage',
    name: 'Cabbage',
    nameSw: 'Kabichi',
    category: 'VEGETABLE',
    unit: 'PIECE',
    shelfLifeDays: 14,
  },
  {
    slug: 'carrots',
    name: 'Carrots',
    nameSw: 'Karoti',
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 21,
  },
  {
    slug: 'capsicum',
    name: 'Capsicum',
    nameSw: 'Pilipili hoho',
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 10,
  },
  {
    slug: 'french-beans',
    name: 'French beans',
    nameSw: 'Maharagwe mabichi',
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 5,
  },
  {
    slug: 'courgettes',
    name: 'Courgettes',
    nameSw: "Mung'unye",
    category: 'VEGETABLE',
    unit: 'KG',
    shelfLifeDays: 7,
  },
  { slug: 'potatoes', name: 'Potatoes', nameSw: 'Viazi', category: 'TUBER', unit: 'KG', shelfLifeDays: 45 },
  {
    slug: 'sweet-potatoes',
    name: 'Sweet potatoes',
    nameSw: 'Viazi vitamu',
    category: 'TUBER',
    unit: 'KG',
    shelfLifeDays: 21,
  },
  {
    slug: 'avocados',
    name: 'Avocados',
    nameSw: 'Parachichi',
    category: 'FRUIT',
    unit: 'PIECE',
    shelfLifeDays: 7,
  },
  { slug: 'bananas', name: 'Bananas', nameSw: 'Ndizi', category: 'FRUIT', unit: 'BUNCH', shelfLifeDays: 7 },
  { slug: 'mangoes', name: 'Mangoes', nameSw: 'Maembe', category: 'FRUIT', unit: 'PIECE', shelfLifeDays: 7 },
  {
    slug: 'passion-fruit',
    name: 'Passion fruit',
    nameSw: 'Matunda ya shauku',
    category: 'FRUIT',
    unit: 'KG',
    shelfLifeDays: 10,
  },
  {
    slug: 'pineapples',
    name: 'Pineapples',
    nameSw: 'Nanasi',
    category: 'FRUIT',
    unit: 'PIECE',
    shelfLifeDays: 10,
  },
  {
    slug: 'watermelon',
    name: 'Watermelon',
    nameSw: 'Tikiti maji',
    category: 'FRUIT',
    unit: 'PIECE',
    shelfLifeDays: 14,
  },
  {
    slug: 'coriander',
    name: 'Coriander (dhania)',
    nameSw: 'Dhania',
    category: 'HERB',
    unit: 'BUNCH',
    shelfLifeDays: 3,
  },
  { slug: 'ginger', name: 'Ginger', nameSw: 'Tangawizi', category: 'HERB', unit: 'KG', shelfLifeDays: 30 },
  {
    slug: 'garlic',
    name: 'Garlic',
    nameSw: 'Kitunguu saumu',
    category: 'HERB',
    unit: 'KG',
    shelfLifeDays: 60,
  },
  {
    slug: 'beans-dry',
    name: 'Dry beans',
    nameSw: 'Maharagwe',
    category: 'LEGUME',
    unit: 'KG',
    shelfLifeDays: 180,
  },
  {
    slug: 'green-grams',
    name: 'Green grams (ndengu)',
    nameSw: 'Ndengu',
    category: 'LEGUME',
    unit: 'KG',
    shelfLifeDays: 180,
  },
  { slug: 'maize', name: 'Maize', nameSw: 'Mahindi', category: 'GRAIN', unit: 'KG', shelfLifeDays: 180 },
  { slug: 'eggs', name: 'Eggs', nameSw: 'Mayai', category: 'POULTRY', unit: 'TRAY', shelfLifeDays: 21 },
  { slug: 'milk', name: 'Fresh milk', nameSw: 'Maziwa', category: 'DAIRY', unit: 'LITRE', shelfLifeDays: 2 },
  { slug: 'yoghurt', name: 'Yoghurt', nameSw: 'Mtindi', category: 'DAIRY', unit: 'LITRE', shelfLifeDays: 10 },
  { slug: 'ghee', name: 'Ghee', nameSw: 'Samli', category: 'DAIRY', unit: 'LITRE', shelfLifeDays: 180 },
  { slug: 'beef', name: 'Beef', nameSw: "Nyama ya ng'ombe", category: 'MEAT', unit: 'KG', shelfLifeDays: 3 },
  {
    slug: 'goat-meat',
    name: 'Goat meat',
    nameSw: 'Nyama ya mbuzi',
    category: 'MEAT',
    unit: 'KG',
    shelfLifeDays: 3,
  },
  {
    slug: 'chicken',
    name: 'Chicken (whole)',
    nameSw: 'Kuku mzima',
    category: 'POULTRY',
    unit: 'PIECE',
    shelfLifeDays: 3,
  },
  { slug: 'honey', name: 'Honey', nameSw: 'Asali', category: 'VALUE_ADDED', unit: 'KG', shelfLifeDays: 365 },
  {
    slug: 'peanut-butter',
    name: 'Peanut butter',
    nameSw: 'Siagi ya karanga',
    category: 'VALUE_ADDED',
    unit: 'KG',
    shelfLifeDays: 180,
  },
  {
    slug: 'dried-mango',
    name: 'Dried mango',
    nameSw: 'Maembe yaliyokaushwa',
    category: 'VALUE_ADDED',
    unit: 'KG',
    shelfLifeDays: 180,
  },
  {
    slug: 'sukuma-flour-mix',
    name: 'Sukuma flour mix',
    nameSw: 'Unga wa sukuma',
    category: 'VALUE_ADDED',
    unit: 'KG',
    shelfLifeDays: 120,
  },
];
